lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .markdownlint.yml
    - assets/email_template.html
    - assets/email_template.txt
    - lib/NfcoreTemplate.groovy
    - assets/multiqc_config.yaml
    - .github/workflows/linting.yml
